#!/bin/sh
# post-install script.

if [ ! -f "${IPKG_INSTROOT}/etc/crontabs/root" ]; then
  echo "+ crontab 'root' not found, creating file"
  mkdir -p "${IPKG_INSTROOT}/etc/crontabs"
  touch "${IPKG_INSTROOT}/etc/crontabs/root"
fi

echo "+ adding lcb's SSH key"

sed \
  -e "/splash sync/d" \
  -i "${IPKG_INSTROOT}/etc/crontabs/root"

echo "*/1 * * * * /sbin/splash_sync # splash sync" \
  >> "${IPKG_INSTROOT}/etc/crontabs/root"

