#!/bin/sh
# post-install script.

if [ ! -f "${IPKG_INSTROOT}/etc/dropbear/authorized_keys" ]; then
  echo "+ file 'authorized_keys' not found, creating file"
  mkdir -p "${IPKG_INSTROOT}/etc/dropbear"
  touch "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"
fi

echo "+ adding egon0's SSH key"

sed \
  -e "/egon0 (Freifunk Jena) <egon0@freifunk-jena.de>/d" \
  -i "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD10olAF5NuYoDoRf2uL7zIOlFE2d46+l0vFrL/BE9PwU6Sum4RXe0h45qYia3Yw2+uj1IhjGGmJnsx1keh3uGCivvYVS9tPeHAuzyx1VlPsnPyUJcBqUGKSDiciUiDBVht0JAeNJxNsqsFb31xfXtp/gasNb1utNBdjCjc41LztqQjL6qu3IEscDa85hZyM+jJGBHDAJ6bFuifxSsxwLHBxRlpPXyqqbMo9VvmOm8qNIYIWea0Qva2OS7djsesh4r9r4bdUryyL4p8Pr/4M1S6ByacxQ4sb/aoGEJmFMZz7y1R+aNsJ1K58fApsFuJftVXGT9yb2coblpe7XQqokmN # egon0 (Freifunk Jena) <egon0@freifunk-jena.de>" \
  >> "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"

