#!/bin/sh
# post-install script.

if [ ! -f "${IPKG_INSTROOT}/etc/dropbear/authorized_keys" ]; then
  echo "+ file 'authorized_keys' not found, creating file"
  mkdir -p "${IPKG_INSTROOT}/etc/dropbear"
  touch "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"
fi

echo "+ adding egon0's SSH key"

sed \
  -e "/egon0 (Freifunk Jena) <egon0@freifunk-jena.de>/d" \
  -i "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD10olAF5NuYoDoRf2uL7zIOlFE2d46+l0vFrL/BE9PwU6Sum4RXe0h45qYia3Yw2+uj1IhjGGmJnsx1keh3uGCivvYVS9tPeHAuzyx1VlPsnPyUJcBqUGKSDiciUiDBVht0JAeNJxNsqsFb31xfXtp/gasNb1utNBdjCjc41LztqQjL6qu3IEscDa85hZyM+jJGBHDAJ6bFuifxSsxwLHBxRlpPXyqqbMo9VvmOm8qNIYIWea0Qva2OS7djsesh4r9r4bdUryyL4p8Pr/4M1S6ByacxQ4sb/aoGEJmFMZz7y1R+aNsJ1K58fApsFuJftVXGT9yb2coblpe7XQqokmN # egon0 (Freifunk Jena) <egon0@freifunk-jena.de>" \
  >> "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmtCmochVLtVGQYc+NBVwQUPSfzth6chAAV6/LiMJ5aT80Mnrihhz49FDoXGzkGgMeJud8c09llZTpFsxpS37ExzqiNclojM3ImrtTF43k0l9tatMUXFtCBsRh4fKpJjbnWlvnv6CjdLkcaTITr4Y+ecBGKSKGoLK6qiVYssfuWmy4I3/o9nwrIAqah3bUR4yjwcoo7e7qyKzck9EjDon1H/SOJsp2UuAGqC0JX6Nwr0tTriZ9ef70F4xHMBglebq1vhsKg2+8PVeMrbYGAv45GjmRwywGEZ4n18ehep+b//++4ZwDGVtcUOzMPhVNsvK23kdNNEKYYm+Tsl8ykaRkXYBB3s38fGuoTofaZXVf5s+6a8DWeTmahqWaskHR4mBNmESu2js4bWvgH+MO9Yi+vYRz/jwgfNl30Q0C9hGtpgIu/6DglHb3Ss948vl5GGi5/iFkpDJmCiheOzs+i3xzxB2yb9cQxNFuJAgI2SNUQ63068J54IILl+WC2VZrIURR7VVaGspq3JYGDEsLSd5uOHFAx36n/CrlQBsbcy2yQYZ8ZE06rahaxAhlvz3LT1M9gUF6hy5MV3lzDkVnMER2nnS6dJZ1ViktwvuwqSSpOXmCBlXVSktSVSlT32Ym295FGyJpqUFrNd/rTwb1SX7arK0YSANRo+Q4k3O1qEEtaw== # egon0-mobi (Freifunk Jena) <egon0@freifunk-jena.de>" \
  >> "${IPKG_INSTROOT}/etc/dropbear/authorized_keys"
