#!/bin/sh
# post-install script.

if [ ! -f "${IPKG_INSTROOT}/etc/crontabs/root" ]; then
  echo "+ crontab 'root' not found, creating file"
  mkdir -p "${IPKG_INSTROOT}/etc/crontabs"
  touch "${IPKG_INSTROOT}/etc/crontabs/root"
fi

echo "+ adding crontab entry"

sed \
  -e "/owm update/d" \
  -i "${IPKG_INSTROOT}/etc/crontabs/root"

echo "0	*	*	*	*	/usr/sbin/owm-update update_map # owm update" \
  >> "${IPKG_INSTROOT}/etc/crontabs/root"
